update resume and improve \'ttaudio\'

diff --git a/bin/ttaudio b/bin/ttaudio
--- a/bin/ttaudio
+++ b/bin/ttaudio
@@ -1,14 +1,40 @@
 #!/bin/bash
 
-bluetooth on
+
+# Turn on bluetooth and set up variables ======================================
+#
+
+bluetooth on &>/dev/null
+
+timeout=10
 ttMAC="E8:AB:FA:23:DA:8F"
-bluetoothCmd="disconnect $ttMAC\nuntrust $ttMAC\ntrust $ttMAC\npair $ttMAC\nconnect $ttMAC"
-echo -e "$bluetoothCmd" | bluetoothctl
-sleep 6
-echo -e "\nquit" | bluetoothctl
 
-clear
+agentCmd="power on\nagent on\n"
+disconnectCmd="disconnect $ttMAC\nuntrust $ttMAC\n"
+connectCmd="trust $ttMAC\npair $ttMAC\nconnect $ttMAC\nquit"
+bluetoothCmd="${agentCmd}${disconnectCmd}${connectCmd}"
 
+
+# Send command and wait for successful connection ==============================
+#
+
+echo -e "$bluetoothCmd" | bluetoothctl &>/dev/null
+
+pactlCmd="pactl list sinks short"
+while [[ -z $(awk '/bluez/ {print $2}' <<< "$($pactlCmd)") ]]; do
+    sleep 1
+    if (( "$SECONDS" >= "$timeout" )); then
+	1>&2
+	printf "%s Error: Exceeded timeout (%d)" "${0##/*/}" "$timeout"
+	exit 1
+    fi    
+done
+
+
+# Set headphones as default output device & enable EQ =========================
+#
+
+printf "Connected to $ttMAC\n"
 ttsink=$(awk '/bluez/ {print $2}' <<< "$(pactl list sinks short)")
 pactl set-default-sink "$ttsink"
 pulseaudio-equalizer enable &>/dev/null
