fix desk \n issue and add nemo-desktop to vis exception list

diff --git a/bash/bin/desk b/bash/bin/desk
--- a/bash/bin/desk
+++ b/bash/bin/desk
@@ -69,10 +69,10 @@ shift $(( OPTIND - 1 ))
 displays=$(xrandr --current | egrep "[0-9]+?x[0-9]+?\+[0-9]+?\+[0-9]+?")
 deskInfo=$(sed "s|\<primary\>||g" <<< "$displays" | awk '{print $3}')
 numDesks=$(wc -l <<< "$deskInfo")
-res=$(sed -r 's|\+\w+||g' <<< "$deskInfo")
+res=$(tr "\n" " " <<< $(sed -r 's|\+\w+||g' <<< "$deskInfo"))
 # res=($(cut -d"x" -f1 <<< "$resStr"))
 # res+=($(cut -d"x" -f2 <<< "$resStr"))
-offset=$(sed -r 's|\w+x\w+\+||g' <<< "$deskInfo")
+offset=$(tr "\n" " " <<< $(sed -r 's|\w+x\w+\+||g' <<< "$deskInfo"))
 
 
 #-------------------------------------------------------------------------------
@@ -81,8 +81,8 @@ offset=$(sed -r 's|\w+x\w+\+||g' <<< "$deskInfo")
 
 if [[ -n $desktop ]]; then
     if [[ $desktop > $numDesks ]]; then
-	echo "Invalid Desktop number requested."
-	exit 1
+		echo "Invalid Desktop number requested."
+		exit 1
     fi
 
     res=$(cut -d" " -f"$desktop" <<< $res)
